services:
  mongo:
    image: mongo:6
    restart: always
    ports: ["27017:27017"]

  api:
    build: .
    depends_on: [mongo]
    environment:
      PORT: 3000
      NODE_ENV: production
      MONGODB_URI: ${MONGODB_URI}
      JWT_SECRET: ${JWT_SECRET}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      S3_KEY: ${S3_KEY}
      S3_SECRET: ${S3_SECRET}
      S3_BUCKET: ${S3_BUCKET}
      UNSPLASH_ID: ${UNSPLASH_ID}
      UNSPLASH_KEY: ${UNSPLASH_KEY}
      UNSPLASH_SECRET: ${UNSPLASH_SECRET}
    ports: ["3000:3000"]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  mongo_data: {}
